<?php $audio_base = base_path() . drupal_get_path('module', 'ybc_education') . '/audio' ?>
<!--suppress ALL -->
<div class="outer">
  <div class="square silent">
    <audio>
      <source src="<?php print $audio_base; ?>/shtumer-alef.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/shtumer-alef.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">א</p>
    <p class="script" dir="rtl">א</p>
    <p class="english" dir="ltr">shtumer alef / silent</p>
    <p class="type"><span>silent</span></p>
  </div>

  <div class="square vowel" id="b2">
    <audio>
      <source src="<?php print $audio_base; ?>/pasekh-alef.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/pasekh-alef.ogg"
              type="audio/ogg">
    </audio>

    <p class="block-letter" dir="rtl">אַ</p>
    <p class="script" dir="rtl">אַ</p>
    <p class="english" dir="ltr">p<span class="accent">a</span>sekh
      alef/ <br/>as in l<span class="accent">a</span>rk</p>
    <p class="type"><span>vowel</span></p>
  </div>


  <div class="square vowel">
    <audio>
      <source src="<?php print $audio_base; ?>/komets-alef.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/komets-alef.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">אָ</p>
    <p class="script" dir="rtl">אָ</p>
    <p class="english" dir="ltr">k<span class="accent">o</span>mets
      aleph/ <br/>as in f<span class="accent">o</span>r</p>
    <p class="type"><span>vowel</span></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/beys.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/beys.ogg"
              type="audio/ogg">
    </audio>

    <p class="block-letter" dir="rtl">ב</p>
    <p class="script" dir="rtl">ב</p>
    <p class="english" dir="ltr"><span class="accent">b</span>eys
    </p>
    <p class="type"><span>consonant</span></p></div>

  <div class="square hebrew">
    <audio>
      <source src="<?php print $audio_base; ?>/veys.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/veys.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">בֿ</p>
    <p class="script" dir="rtl">בֿ</p>
    <p class="english" dir="ltr"><span class="accent">v</span>eys</p>
    <p class="type"><span>hebrew only</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/giml.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/giml.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ג</p>
    <p class="script" dir="rtl">ג</p>
    <p class="english" dir="ltr"><span class="accent">g</span>iml/ <br/>as in
      <span class="accent">g</span>irl</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/daled.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/daled.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ד</p>
    <p class="script" dir="rtl">ד</p>
    <p class="english" dir="ltr"><span class="accent">d</span>aled</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/hey.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/hey.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ה</p>
    <p class="script" dir="rtl">ה</p>
    <p class="english" dir="ltr"><span class="accent">h</span>ey</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square vowel">
    <audio>
      <source src="<?php print $audio_base; ?>/vov.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/vov.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ו</p>
    <p class="script" dir="rtl">ו</p>
    <p class="english" dir="ltr">vov/ <br/>as in m<span class="accent">oo</span>n
    </p>
    <p class="type"><span>vowel</span></p></div>


  <div class="square vowel">
    <audio>
      <source src="<?php print $audio_base; ?>/melupm-vov.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/melupm-vov.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">וּ</p>
    <p class="script" dir="rtl">וּ</p>
    <p class="english" dir="ltr">melupm vov/ <br/>as in m<span
        class="accent">oo</span>n</p>
    <p class="type"><span>vowel</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/tsvey-vovn.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/tsvey-vovn.ogg"
              type="audio/ogg">
    </audio>

    <p class="block-letter" dir="rtl">װ</p>
    <p class="script" dir="rtl">װ</p>
    <p class="english" dir="ltr">tsvey <span class="accent">v</span>ovn</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square dipthong">
    <audio>
      <source src="<?php print $audio_base; ?>/vov-yud.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/vov-yud.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">וי</p>
    <p class="script" dir="rtl">וי</p>
    <p class="english" dir="ltr">vov yud/ <br/>as in b<span
        class="accent">oy</span></p>
    <p class="type"><span>dipthong</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/zayen.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/zayen.ogg"
              type="audio/ogg">
    </audio>

    <p class="block-letter" dir="rtl">ז</p>
    <p class="script" dir="rtl">ז</p>
    <p class="english" dir="ltr"><span class="accent">z</span>ayen</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square hebrew">
    <audio>
      <source src="<?php print $audio_base; ?>/khes.ogg"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/khes.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ח</p>
    <p class="script" dir="rtl">ח</p>
    <p class="english" dir="ltr"><span class="accent">kh</span>es/ <br/>as in
      Irish lo<span class="accent">ch</span></p>
    <p class="type"><span>hebrew only</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/tes.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/tes.mp3"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ט</p>
    <p class="script" dir="rtl">ט</p>
    <p class="english" dir="ltr"><span class="accent">t</span>es</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant-vowel">
    <audio>
      <source src="<?php print $audio_base; ?>/yud.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/yud.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">י</p>
    <p class="script" dir="rtl">י</p>
    <p class="english" dir="ltr"><span class="accent">y</span>ud/ <br/>as in
      <span class="accent">y</span>es, as in g<span class="accent">i</span>ve or
      as in l<span class="accent">ea</span>ve</p>
    <p class="type"><span>vowel/consonant</span></p></div>


  <div class="square vowel">
    <audio>
      <source src="<?php print $audio_base; ?>/khirek-yud.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/khirek-yud.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">יִ</p>
    <p class="script" dir="rtl">יִ</p>
    <p class="english" dir="ltr">khirek yud/ <br/>as in g<span
        class="accent">i</span>ve<br/> or as in l<span class="accent">ea</span>ve
    </p>
    <p class="type"><span>vowel</span></p></div>


  <div class="square dipthong">
    <audio>
      <source src="<?php print $audio_base; ?>/tsvey-yudn.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/tsvey-yudn.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">יי</p>
    <p class="script" dir="rtl">יי</p>
    <p class="english" dir="ltr">tsvey yudn/ <br/>as in w<span
        class="accent">ei</span>gh</p>
    <p class="type"><span>dipthong</span></p></div>


  <div class="square dipthong">
    <audio>
      <source src="<?php print $audio_base; ?>/pasekh-tsvey-yudn.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/pasekh-tsvey-yudn.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ײַ</p>
    <p class="script" dir="rtl">ײַ</p>
    <p class="english" dir="ltr">pasekh tsvey yudn/ <br/>as in fl<span
        class="accent">y</span></p>
    <p class="type"><span>dipthong</span></p></div>


  <div class="square hebrew">
    <audio>
      <source src="<?php print $audio_base; ?>/kof.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/kof.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">כּ</p>
    <p class="script" dir="rtl">כּ</p>
    <p class="english" dir="ltr"><span class="accent">k</span>of</p>
    <p class="type"><span>hebrew only</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/khof.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/khof.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">כ
    </p>
    <p class="script" dir="rtl">כ</p>
    <p class="english" dir="ltr"><span class="accent">kh</span>of/<br/>as in
      Irish lo<span class="accent">ch</span></p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square final">
    <audio>
      <source src="<?php print $audio_base; ?>/langer-khof.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/langer-khof.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ך
    </p>
    <p class="script" dir="rtl">ך</p>
    <p class="english" dir="ltr">langer <span class="accent">kh</span>of/ <br/>as
      in Irish lo<span class="accent">ch</span></p>
    <p class="type"><span>final form</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/lamed.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/lamed.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ל
    </p>
    <p class="script" dir="rtl">ל</p>
    <p class="english" dir="ltr"><span class="accent">l</span>amed</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/mem.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/mem.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">מ
    </p>
    <p class="script" dir="rtl">מ</p>
    <p class="english" dir="ltr"><span class="accent">m</span>em</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square final">
    <audio>
      <source src="<?php print $audio_base; ?>/shlos-mem.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/shlos-mem.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ם
    </p>
    <p class="script" dir="rtl">ם</p>
    <p class="english" dir="ltr">shlos <span class="accent">m</span>em</p>
    <p class="type"><span>final form</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/nun.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/nun.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">נ
    </p>
    <p class="script" dir="rtl">נ</p>
    <p class="english" dir="ltr"><span class="accent">n</span>un</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square final">
    <audio>
      <source src="<?php print $audio_base; ?>/langer-nun.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/langer-nun.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ן
    </p>
    <p class="script" dir="rtl">ן</p>
    <p class="english" dir="ltr">langer <span class="accent">n</span>un</p>
    <p class="type"><span>final form</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/samekh.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/samekh.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ס
    </p>
    <p class="script" dir="rtl">ס</p>
    <p class="english" dir="ltr"><span class="accent">s</span>amekh</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square vowel">
    <audio>
      <source src="<?php print $audio_base; ?>/ayen.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/ayen.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ע
    </p>
    <p class="script" dir="rtl">ע</p>
    <p class="english" dir="ltr">ayen/ <br/>as in b<span class="accent">e</span>d
    </p>
    <p class="type"><span>vowel</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/pey.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/pey.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">פּ
    </p>
    <p class="script" dir="rtl">פּ</p>
    <p class="english" dir="ltr"><span class="accent">p</span>ey</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/fey.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/fey.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">פֿ
    </p>
    <p class="script" dir="rtl">פֿ</p>
    <p class="english" dir="ltr"><span class="accent">f</span>ey</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square final">
    <audio>
      <source src="<?php print $audio_base; ?>/langer-fey.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/langer-fey.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ף
    </p>
    <p class="script" dir="rtl">ף</p>
    <p class="english" dir="ltr">langer <span class="accent">f</span>ey</p>
    <p class="type"><span>final form</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/tsadek.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/tsadek.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">צ
    </p>
    <p class="script" dir="rtl">צ</p>
    <p class="english" dir="ltr"><span class="accent">ts</span>adek</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square final">
    <audio>
      <source src="<?php print $audio_base; ?>/langer-tsadek.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/langer-tsadek.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ץ
    </p>
    <p class="script" dir="rtl">ץ</p>
    <p class="english" dir="ltr">langer <span class="accent">ts</span>adek</p>
    <p class="type"><span>final form</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/kuf.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/kuf.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ק
    </p>
    <p class="script" dir="rtl">ק</p>
    <p class="english" dir="ltr"><span class="accent">k</span>uf</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/reysh.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/reysh.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ר
    </p>
    <p class="script" dir="rtl">ר</p>
    <p class="english" dir="ltr"><span class="accent">r</span>eysh</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/shin.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/shin.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ש
    </p>
    <p class="script" dir="rtl">ש</p>
    <p class="english" dir="ltr"><span class="accent">sh</span>in</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square hebrew">
    <audio>
      <source src="<?php print $audio_base; ?>/sin.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/sin.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">שׂ
    </p>
    <p class="script" dir="rtl">שׂ</p>
    <p class="english" dir="ltr"><span class="accent">s</span>in</p>
    <p class="type"><span>hebrew only</span></p></div>


  <div class="square hebrew">
    <audio>
      <source src="<?php print $audio_base; ?>/tof.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/tof.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">תּ
    </p>
    <p class="script" dir="rtl">תּ</p>
    <p class="english" dir="ltr"><span class="accent">t</span>of</p>
    <p class="type"><span>hebrew only</span></p></div>


  <div class="square hebrew">
    <audio>
      <source src="<?php print $audio_base; ?>/sof.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/sof.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">ת
    </p>
    <p class="script" dir="rtl">ת</p>
    <p class="english" dir="ltr"><span class="accent">s</span>of</p>
    <p class="type"><span>hebrew only</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/daled-zayen-shin.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/daled-zayen-shin.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">דזש
    </p>
    <p class="script" dir="rtl">דזש</p>
    <p class="english" dir="ltr">daled zayen shin/ <br/>as in <span
        class="accent">j</span>ar</p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/zayen-shin.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/zayen-shin.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">זש
    </p>
    <p class="script" dir="rtl">זש</p>
    <p class="english" dir="ltr">zayen shin/ <br/>as in bei<span class="accent">g</span>e
    </p>
    <p class="type"><span>consonant</span></p></div>


  <div class="square consonant">
    <audio>
      <source src="<?php print $audio_base; ?>/tes-shin.mp3"
              type="audio/mpeg">
      <source src="<?php print $audio_base; ?>/tes-shin.ogg"
              type="audio/ogg">
    </audio>
    <p class="block-letter" dir="rtl">טש
    </p>
    <p class="script" dir="rtl">טש</p>
    <p class="english" dir="ltr">tes shin/ <br/>as in <span
        class="accent">ch</span>eese</p>
    <p class="type"><span>consonant</span></p></div>

</div>
