<div class="horizontal-quiz">
  <div class="question-horizontal">
    <div class="question-wrapper">
      <ul class="letter">
        <li>נ</li>
        <li>ג</li>
      </ul>

      <ul class="horizontal-prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
      </ul>
    </div>
    <div class="reply-wrapper">
      <ul>
        <li class="long-box-reply" data-value="1">nun (n)</li>
        <li class="long-box-reply" data-value="2">gimel (g)</li>
      </ul>
    </div>
  </div>

  <div class="question-horizontal">
    <div class="question-wrapper">
      <ul class="letter">
        <li>ב</li>
        <li>כ</li>
      </ul>

      <ul class="horizontal-prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
      </ul>
    </div>
    <div class="reply-wrapper">
      <ul>
        <li class="long-box-reply" data-value="1">beys (b)</li>
        <li class="long-box-reply" data-value="2"> khof (kh/ch)</li>
      </ul>
    </div>
  </div>

  <div class="question-horizontal">
    <div class="question-wrapper">
      <ul class=letter>
        <li>ס</li>
        <li>ם</li>
      </ul>
      <ul class="horizontal-prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
      </ul>
    </div>
    <div class="reply-wrapper">
      <ul>
        <li class="long-box-reply" data-value="1">samekh (s)</li>
        <li class="long-box-reply" data-value="2">shlos mem (m)</li>
      </ul>
    </div>
  </div>

  <div class="question-horizontal">
    <div class="question-wrapper">
      <ul class="letter">
        <li>ה</li>
        <li>ח</li>
      </ul>
      <ul class="horizontal-prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
      </ul>
    </div>
    <div class="reply-wrapper">
      <ul>
        <li class="long-box-reply" data-value="2">khes (kh/ch)</li>
        <li class="long-box-reply" data-value="1">hey (h)</li>
      </ul>

    </div>
  </div>

  <div class="question-horizontal">
    <div class="question-wrapper">
      <ul class=letter>
        <li>ד</li>
        <li>ר</li>
      </ul>
      <ul class="horizontal-prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
      </ul>

    </div>
    <div class="reply-wrapper">
      <ul>
        <li class="long-box-reply" data-value="1">daled (d)</li>
        <li class="long-box-reply" data-value="2">reysh (r)</li>
      </ul>
    </div>
  </div>

  <div class="question-horizontal">
    <div class="question-wrapper">
      <ul class="letter">
        <li>ו</li>
        <li>ן</li>
      </ul>
      <ul class="horizontal-prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
      </ul>
    </div>
    <div class="reply-wrapper">
      <ul>
        <li class="long-box-reply" data-value="1">vov (u)</li>
        <li class="long-box-reply" data-value="2">langer nun (n)</li>
      </ul>
    </div>
  </div>

  <div class="question-horizontal">
    <div class="question-wrapper">
      <ul class="letter">
        <li>ז</li>
        <li>ו</li>
      </ul>
      <ul class="horizontal-prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
      </ul>
    </div>
    <div class="reply-wrapper" style="border-bottom: 0">
      <ul>
        <li class="long-box-reply" data-value="1">zayen (z)</li>
        <li class="long-box-reply" data-value="2">vov (u)</li>
      </ul>
    </div>
  </div>
  <div class="button">
    <button class="checkAnswersHorizontal" class="button-primary">Check answers
    </button>
    <button class="reload" class="webform-submit">Reload exercise</button>
  </div>
  <div class="dialog"></div>
</div>

