<?php $audio_base = base_path() . drupal_get_path('module', 'ybc_education') . '/audio' ?>
<!--suppress ALL -->


<div class="lesson">
  <h2 class="center">The Vowels</h2>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-1-vowels.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-1-vowels.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or
      greater.
      To download the audio file instead <a
        href="audio/reading-practice-1-vowels.mp3">click here</a>.
    </audio>

    <p style="line-height: 1.2em;">
      <span class="letter">א</span>
      <span class="gloss" title="a" STYLE="font-size: 32px">אַ</span>
      <span class="letter">אָ</span>
      <span class="letter">ע</span>
      <span class="letter">י</span>
      <span class="letter">ו</span>
    </p>

    <p style="line-height: 1.2em;">
      <span class="letter">וי</span>
      <span class="letter">יי</span>
      <span class="letter"> ײַ</span>
    </p>

    <p>
      <span class="phrase">אי</span>
      <span class="phrase">או</span>
      <span class="phrase">אוי</span>
      <span class="phrase">איי</span>
      <span class="phrase">אײַ</span>
      <span class="phrase">אוי־אוי־אוי</span>
      <span class="phrase">אײַ־אײַ־אײַ</span>
    </p>
  </div>

  <h2 class="center">The Consonants</h2>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-2-daled.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-2-daled.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-2-daled.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ד</span>
      <span class="gloss" title="the(f)">די</span>
      <span class="gloss" title="idea">אידעע</span>
      <span class="gloss" title="here">דאָ</span>
      <span class="gloss" title="you">דו</span>
      <span class="phrase">(די אידעע)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source src="<?php print $audio_base; ?>/reading-practice-3-yud.ogg"
              type="audio/ogg">
      <source src="<?php print $audio_base; ?>/reading-practice-3-yud.mp3"
              type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-3-yud.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">י</span>
      <span class="gloss" title="Jew">ייִד</span>
      <span class="gloss" title="yes">יאָ</span>
      <span class="phrase">(אַ ייִד?)</span>
      <span class="phrase">(יאָ, אַ ייִד!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-4-zayen.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-4-zayen.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-4-zayen.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ז</span>
      <span class="gloss" title="is">איז</span>
      <span class="gloss" title="see(imp)">זע</span>
      <span class="gloss" title="grandpa">זיידע</span>
      <span class="phrase">(אַ זיידע)</span>
      <span class="gloss" title="she">זי</span>
      <span class="gloss" title="so, like this">אַזוי</span>
      <span class="phrase">(זי איז אַזוי.)</span>
      <span class="gloss" title="they">זיי</span>
      <span class="gloss" title="when, if">אַז</span>
      <span class="phrase">(דאָ איז אַ ייִד!)</span>
      <span class="phrase">(זע! דאָ איז זײדע.)</span>
      <span class="phrase">(זײדע איז אַ ייִד.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-5-beys.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-5-beys.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-5-beys.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ב</span>
      <span class="gloss" title="grandma">באָבע</span>
      <span class="phrase">(די באָבע)</span>
      <span class="gloss" title="angry">בייז</span>
      <span class="gloss" title="by">בײַ</span>
      <span class="gloss" title="if">אױב</span>
      <span class="phrase">(זי איז אַ באָבע.)</span>
      <span class="phrase">(די באָבע איז דאָ.)</span>
      <span class="phrase">(די באָבע איז בייז.)</span>
      <span class="phrase">(זי איז אַזוי בייז!)</span>
      <span class="phrase">(די באָבע איז בײז אַז זײדע איז דאָ.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-6-reysh.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-6-reysh.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-6-reysh.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ר</span>
      <span class="gloss" title="the(m)">דער</span>
      <span class="phrase">(דער ייִד)</span>
      <span class="phrase">(דער זיידע)</span>
      <span class="gloss" title="bear">בער</span>
      <span class="phrase">(דער בער)</span>
      <span class="gloss" title="he">ער</span>
      <span class="gloss" title="very; their">זייער</span>
      <span class="phrase">(ער איז זייער בייז!)</span>
      <span class="gloss" title="but">אָבער</span>
      <span class="gloss" title="brother">ברודער</span>
      <span class="phrase">(דער ברודער)</span>
      <span class="gloss" title="or">אָדער</span>
      <span class="gloss" title="pear">באַר</span>
      <span class="phrase">(די באַר)</span>
      <span class="gloss" title="sour">זויער</span>
      <span class="gloss" title="lake">אָזערע</span>
      <span class="phrase">(די אָזערע)</span>
      <span class="gloss" title="you(formal, pl)">איר</span>
      <span class="phrase">(דער בער איז דאָ! ער איז זײער בײז!)</span>
      <span class="phrase">(אױב דער בער איז דאָ, איז די באָבע בײז!)</span>
      <span class="phrase">(זי איז אַ באָבע, אָבער ער איז אַ בער.)</span>
      <span class="phrase">(דאָ איז דער ברודער.)</span>
      <span class="phrase">(ער איז דער ברודער, אָדער דער זײדע?)</span>
      <span class="phrase">(ער איז דער ברודער.)</span>
      <span class="phrase">(דאָ איז אַ באַר.)</span>
      <span class="phrase">(די באַר איז זויער?)</span>
      <span class="phrase">(זי איז זײער זױער!)</span>
      <span class="phrase">(דאָ איז אַ באַר אָדער אַ בער?)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source src="<?php print $audio_base; ?>/reading-practice-7-nun.ogg"
              type="audio/ogg">
      <source src="<?php print $audio_base; ?>/reading-practice-7-nun.mp3"
              type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-7-nun.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">נ</span>
      <span class="gloss" title="fool">נאַר</span>
      <span class="phrase">(דער נאַר)</span>
      <span class="gloss" title="only, but">נאָר</span>
      <span class="gloss" title="nu">נו</span>
      <span class="gloss" title="banana">באַנאַנע</span>
      <span class="phrase">(די באַנאַנע)</span>
      <span class="gloss" title="nose">נאָז</span>
      <span class="phrase">(די נאָז)</span>
      <span class="phrase">(דער ייִד איז אַ נאַר.)</span>
      <span class="phrase">(דער זײדע איז אַ נאַר?)</span>
      <span class="phrase">(נאָר דער ייִד איז אַ נאַר.)</span>
      <span class="phrase">(נו, די באַנאַנע איז דאָ?)</span>
    </p>
  </div>

  <div class="section">
    <audio controls="">
      <source
        src="<?php print $audio_base; ?>/reading-practice-8-langernun.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-8-langernun.mp3"
        type="audio/mpeg">
      Your
      browser does not support the audio element. Please use a recent version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-8-langernun.mp3">click
        here</a>.
    </audio>

    <p>
      <span class="letter">ן</span>
      <span class="gloss" title="no">ניין</span>
      <span class="gloss" title="your">דײַן</span>
      <span class="gloss" title="in">אין</span>
      <span class="gloss" title="clean">ריין</span>
      <span class="gloss" title="his">זײַן</span>
      <span class="gloss" title="and">און</span>
      <span class="phrase">(אַ באַר און אַ באַנאַנע)</span>
      <span class="gloss" title="talk, speak">רעדן</span>
      <span class="phrase">(זיי רעדן.)</span>
      <span class="gloss" title="an">אַן</span>
      <span class="phrase">(אַן אידעע)</span>
      <span class="gloss" title="see(pl)">זעען</span>
      <span class="phrase">(זיי זעען.)</span>
      <span class="gloss" title="am">בין</span>
      <span class="gloss" title="are">זײַנען</span>
      <span class="phrase">(זײ זײַנען דאָ.)</span>
      <span class="phrase">(נײן, דײַן באַנאַנע איז אין דער אָזערע.)</span>
      <span class="phrase">(די באַנאַנע איז רײן?)</span>
      <span class="phrase">(נײן, אָבער זײַן באַר איז רײן.)</span>
      <span class="phrase">(די באָבע און דער ברודער רעדן.)</span>
      <span class="phrase">(אָ! רײנע איז דאָ!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls="">
      <source
        src="<?php print $audio_base; ?>/reading-practice-9-samekh.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-9-samekh.mp3"
        type="audio/mpeg">
      Your
      browser does not support the audio element. Please use a recent version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-9-samekh.mp3">click
        here</a>.
    </audio>

    <p>
      <span class="letter">ס</span>
      <span class="gloss" title="eat; it">עס</span>
      <span class="phrase">(עס איז דאָ)</span>
      <span class="gloss" title="the(n); this">דאָס</span>
      <span class="gloss" title="sweet">זיס</span>
      <span class="gloss" title="outside">דרױסן</span>
      <span class="phrase">(אין דרױסן)</span>
      <span class="gloss" title="better">בעסער</span>
      <span class="phrase">(דאָס איז בעסער.)</span>
      <span class="gloss" title="eat(pl)">עסן</span>
      <span class="phrase">(זײ עסן)</span>
      <span class="phrase">(רײנע, עס איז דאָ אַ בער!)</span>
      <span class="phrase">(דאָס איז זײַן נאָז!)</span>
      <span class="phrase">(עס איז דאָ אַ באַר. זי איז זיס?)</span>
      <span class="phrase">(נײן, זײַן באַר איז זױער.)</span>
      <span class="phrase">(זײַן נאָז איז רײן?)</span>
      <span class="phrase">(דער בער איז אין דרױסן!)</span>
      <span class="phrase">(בעסער אַזױ!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls="">
      <source
        src="<?php print $audio_base; ?>/reading-practice-10-lamed.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-10-lamed.mp3"
        type="audio/mpeg">
      Your
      browser does not support the audio element. Please use a recent version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-10-lamed.mp3">click
        here</a>.
    </audio>

    <p>
      <span class="letter">ל</span>
      <span class="gloss" title="ball">באַל</span>
      <span class="phrase">(דער באַל)</span>
      <span class="gloss" title="blue">בלוי</span>
      <span class="phrase">(דער בלױער באַל)</span>
      <span class="gloss" title="pencil">בלײַער</span>
      <span class="phrase">(דער בלײַער)</span>
      <span class="gloss" title="purple">לילאַ</span>
      <span class="phrase">(דער לילאַ בלײַער)</span>
      <span class="gloss" title="should">זאָל</span>
      <span class="phrase">(ער זאָל)</span>
      <span class="phrase">(ער זאָל עסן.)</span>
      <span class="gloss" title="read">לײענען</span>
      <span class="phrase">(זיי לײענען.)</span>
      <span class="gloss" title="alone">אַליין</span>
      <span class="phrase">(ער איז אַלײן.)</span>
      <span class="gloss" title="song">ליד</span>
      <span class="phrase">(דאָס ליד)</span>
      <span class="gloss" title="songs">לידער</span>
      <span class="phrase">(די לידער)</span>
      <span class="gloss" title="London">לאָנדאָן</span>
      <span class="phrase">(ער איז אין לאָנדאָן.)</span>
      <span class="gloss" title="rock-a-bye">אײַ־ליו־ליו</span>
      <span class="gloss" title="love">ליבע</span>
      <span class="phrase">(די ליבע)</span>
      <span class="gloss" title="teacher(m)">לערער</span>
      <span class="phrase">(דער לערער)</span>
      <span class="phrase">(דער זײדע איז אַ לערער.)</span>
      <span class="gloss" title="teacher(f)">לערערין</span>
      <span class="phrase">(די לערערין)</span>
      <span class="phrase">(די באָבע איז אַ לערערין.)</span>
      <span class="phrase">(דאָס איז רײנעס באַל. איר באַל איז בלױ.)</span>
      <span class="phrase">(דער בלױער באַל איז רײן!)</span>
      <span class="phrase">(דאָס איז רײנעס בלײַער. איר בלײַער איז לילאַ.)</span>
      <span class="phrase">(דער לילאַ בלײַער איז רײן!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-11-tes.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-11-tes.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-11-tes.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ט</span>
      <span class="gloss" title="dad">טאַטע</span>
      <span class="phrase">(דער טאַטע)</span>
      <span class="gloss" title="eats">עסט</span>
      <span class="phrase">(ער עסט)</span>
      <span class="gloss" title="bread">ברויט</span>
      <span class="phrase">(דער ברויט)</span>
      <span class="gloss" title="red">רויט</span>
      <span class="gloss" title="work, works">אַרבעט</span>
      <span class="phrase">(די אַרבעט)</span>
      <span class="gloss" title="interesting">אינטערעסאַנט</span>
      <span class="gloss" title="should">זאָלסט</span>
      <span class="phrase">(דו זאָלסט)</span>
      <span class="phrase">(דו זאָלסט עסן.)</span>
      <span class="gloss" title="bed">בעט</span>
      <span class="phrase">(די בעט)</span>
      <span class="gloss" title="there">דאָרטן</span>
      <span class="gloss" title="sees">זעט</span>
      <span class="phrase">(ער זעט)</span>
      <span class="gloss" title="reads">לײענט</span>
      <span class="phrase">(ער לײענט)</span>
      <span class="gloss" title="are">זײַט</span>
      <span class="phrase">(איר זײַט דאָ?)</span>
      <span class="gloss" title="Boston">באָסטאָן</span>
      <span class="gloss" title="tea">טיי</span>
      <span class="phrase">(דער טיי)</span>
      <span class="gloss" title="here">אָט</span>
      <span class="phrase">(אָט איז ער.)</span>
      <span class="gloss" title="work">אַרבעטן</span>
      <span class="phrase">(זײ אַרבעטן אין דרױסן.)</span>
      <span class="phrase">(דער טאַטע איז דאָ!)</span>
      <span class="phrase">(ער עסט ברױט!)</span>
      <span class="phrase">(טאַטע, דײַן נאָז איז רױט!)</span>
      <span class="phrase">(דער טאַטע אַרבעט אין דרױסן. זײַן אַרבעט איז אינטערעסאַנט.)</span>
      <span
        class="phrase">(טאַטע, זאָלסט זײַן אין בעט. די בעט איז דאָרטן.)</span>
      <span class="phrase">(די בעט איז רײן!)</span>
      <span class="phrase">(דער טאַטע זעט אַז די בעט איז רײן.)</span>
      <span class="phrase">(דער טאַטע לײענט אין דער בעט. ער איז אַלײן.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-12-tsveyvovn.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-12-tsveyvovn.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-12-tsveyvovn.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">וו</span>
      <span class="gloss" title="who">ווער</span>
      <span class="phrase">(װער איז דאָס?)</span>
      <span class="gloss" title="white">װײַס</span>
      <span class="gloss" title="what">וואָס</span>
      <span class="phrase">(װאָס איז דאָס?)</span>
      <span class="gloss" title="lives">װױנט</span>
      <span class="phrase">(זי װױנט אין באָסטאָן.)</span>
      <span class="gloss" title="university">אוניװערסיטעט</span>
      <span class="phrase">(דער אוניװערסיטעט)</span>
      <span class="gloss" title="where">וווּ</span>
      <span class="phrase">(װוּ איז ער?)</span>
      <span class="gloss" title="want">װילסט</span>
      <span class="phrase">(דו װילסט)</span>
      <span class="phrase">(דו װילסט עסן?)</span>
      <span class="gloss" title="water">װאַסער</span>
      <span class="phrase">(דאָס וואַסער)</span>
      <span class="gloss" title="how; than">װי</span>
      <span class="phrase">(דער טײ איז בעסער װי װאַסער.)</span>
      <span class="phrase">(װער איז אין דער בעט?)</span>
      <span
        class="phrase">(דער טאַטע איז אין דער בעט. זײַן בעט איז װײַס.)</span>
      <span class="phrase">(װאָס לײענט דער טאַטע?)</span>
      <span class="phrase">(ער לײענט רײזענס לידער.)</span>
      <span class="phrase">(װער זײַט איר?)</span>
      <span class="phrase">(װעלװל.)</span>
      <span class="phrase">(ער איז אַ ייִד!)</span>
      <span class="phrase">(איר װױנט אין לאָנדאָן?)</span>
      <span class="phrase">(נײן, אין באָסטאָן.)</span>
      <span class="phrase">(עס איז דאָ אַן אוניװערסיטעט אין באָסטאָן?)</span>
      <span class="phrase">(יאָ.)</span>
      <span class="phrase">(װוּ איז דער ברודער?)</span>
      <span class="phrase">(דער ברודער איז אין דרױסן.)</span>
      <span class="phrase">(טאַטע, דו װילסט װאַסער אָדער טײ?)</span>
      <span class="phrase">(דער טײ איז זיס, אָבער דאָס וואַסער איז ריין.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-13-gimel.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-13-gimel.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-13-gimel.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ג</span>
      <span class="gloss" title="good">גוט</span>
      <span class="phrase">(זײער גוט!)</span>
      <span class="phrase">(זײַ אַזױ גוט)</span>
      <span class="gloss" title="green">גרין</span>
      <span class="phrase">(די באַנאַנע איז גרין.)</span>
      <span class="gloss" title="guitar">גיטאַרע</span>
      <span class="phrase">(די גיטאַרע)</span>
      <span class="gloss" title="garden">גאָרטן</span>
      <span class="phrase">(דער גאָרטן)</span>
      <span class="gloss" title="sing(pl)">זינגען</span>
      <span class="phrase">(זײ זינגען אַ ליד.)</span>
      <span class="gloss" title="bring">ברענג</span>
      <span class="phrase">(זײַ אַזױ גוט און ברענג דאָס װאַסער.)</span>
      <span class="gloss" title="big">גרויס</span>
      <span class="gloss" title="lullaby">װיגליד</span>
      <span class="phrase">(דאָס װיגליד)</span>
      <span class="gloss" title="was">געװען</span>
      <span class="phrase">(זי איז געװען דאָ.)</span>
      <span class="gloss" title="goes">גייט</span>
      <span class="phrase">(ער גײט)</span>
      <span class="gloss" title="go(pl)">גײען</span>
      <span class="phrase">(זײ גײען אין אוניװערסיטעט.)</span>
      <span class="gloss" title="say">זאָגן</span>
      <span class="phrase">(די באַרן זײַנען גרױס? זײ זאָגן אַזױ!)</span>
      <span class="phrase">(טאַטע, דו װילסט װאַסער אָדער טײ?)</span>
      <span class="phrase">(טײ, זײַ אַזױ גוט.)</span>
      <span class="phrase">(דער טײ איז גרין.)</span>
      <span class="phrase">(זײער גוט.)</span>
      <span class="phrase">(זײדע, װוּ איז דײַן גיטאַרע?)</span>
      <span class="phrase">(די גיטאַרע איז אין גאָרטן. דו װילסט זינגען?)</span>
      <span class="phrase">(רײנע, ברענג די גיטאַרע.)</span>
      <span class="phrase">(די גיטאַרע איז גרויס!)</span>
      <span class="phrase">(זינג, רײנע!)</span>
      <span class="phrase">(אײַ־ליו־ליו, אײַ־ליו־ליו...)</span>
      <span class="phrase">(דאָס איז אַ װיגליד.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-14-mem.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-14-mem.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-14-mem.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">מ</span>
      <span class="gloss" title="tired">מיד</span>
      <span class="gloss" title="mom">מאַמע</span>
      <span class="phrase">(די מאַמע)</span>
      <span class="gloss" title="with">מיט</span>
      <span class="gloss" title="coat">מאַנטל</span>
      <span class="phrase">(דער מאַנטל)</span>
      <span class="gloss" title="my">מײַן</span>
      <span class="gloss" title="girl">מײדל</span>
      <span class="phrase">(דאָס מײדל)</span>
      <span class="gloss" title="man">מאַן</span>
      <span class="phrase">(דער מאַן)</span>
      <span class="phrase">(דער מאַן גײט אין גאָרטן.)</span>
      <span class="gloss" title="name">נאָמען</span>
      <span class="phrase">(מײַן נאָמען איז מירל.)</span>
      <span class="gloss" title="lets">לאָמיר</span>
      <span class="phrase">(לאָמיר גײן אין דרױסן.)</span>
      <span class="gloss" title="we">מיר</span>
      <span class="phrase">(מיר לײענען אין דרױסן.)</span>
      <span class="phrase">(ער איז זײער מיד...)</span>
      <span class="phrase">(די מאַמע איז דאָ מיט איר מאַנטל!)</span>
      <span class="phrase">(רײנע! מײַן מײדל!)</span>
  <span
    class="phrase">(מאַמע, עס איז דאָ אַ מאַן אין דער בעט. ער איז מיד.)</span>
      <span class="phrase">(װאָס איז זײַן נאָמען?)</span>
      <span class="phrase">(זײַן נאָמען איז װעלװל.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-15-shlosmem.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-15-shlosmem.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-15-shlosmem.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ם</span>
      <span class="gloss" title="flower">בלום</span>
      <span class="phrase">(די בלום)</span>
      <span class="gloss" title="the(acc, dat)">דעם</span>
      <span class="phrase">(מיר רעדן מיט דעם מאַן.)</span>
      <span class="gloss" title="tree">בוים</span>
      <span class="phrase">(דער בוים)</span>
      <span class="phrase">(דער בוים איז גרויס.)</span>
      <span class="phrase">(זײ זעען דעם בױם.)</span>
      <span class="gloss" title="pleasant">אײַנגענעם</span>
      <span class="phrase">(זײער אײַנגענעם!)</span>
      <span class="gloss" title="take">נעם</span>
      <span class="phrase">(נעם די בלום.)</span>
      <span class="phrase">(רײנע, אָט איז דײַן בלום.)</span>
      <span class="phrase">(אָ! זי איז רױט און גרין!)</span>
      <span class="phrase">(די בלום איז געװען אין גאָרטן מיט דעם בױם.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-16-shin.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-16-shin.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-6-shin.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ש</span>
      <span class="gloss" title="pretty">שיין</span>
      <span class="phrase">(די בלום איז שיין.)</span>
      <span class="gloss" title="table">טיש</span>
      <span class="phrase">(דער טיש)</span>
      <span class="gloss" title="stands">שטייט</span>
      <span class="phrase">(זי שטײט.)</span>
      <span class="gloss" title="heavy, difficult">שװער</span>
      <span class="gloss" title="writes">שרײַבט</span>
      <span class="phrase">(די לערעריןשרײַבט.)</span>
      <span class="gloss" title="not">נישט</span>
      <span class="phrase">(ער שרײַבט נישט.)</span>
      <span class="phrase">(זי איז אַזױ שײן!)</span>
      <span class="phrase">(װוּ איז דער טיש?)</span>
      <span class="phrase">(דער טיש שטײט דאָרטן.)</span>
      <span class="phrase">(רײנע, זײַ אַזױ גוט און ברענג דעם טיש.)</span>
      <span class="phrase">(אָבער ער איז אַזױ שװער!)</span>
      <span class="phrase">(טאַטע, ברענג דעם טיש מיט רײנען.)</span>
      <span class="phrase">(דער טיש איז רײן!)</span>
      <span class="phrase">(מאַמע, דאָס איז װעלװל.)</span>
      <span class="phrase">(זײער אײַנגענעם!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-17-kuf.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-17-kuf.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-17-kuf.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ק</span>
      <span class="gloss" title="child">קינד</span>
      <span class="phrase">(דאָס קינד)</span>
      <span class="gloss" title="can">קען</span>
      <span class="phrase">(דאָס קינד קען לײענען אַ בוך.)</span>
      <span class="gloss" title="small">קלײן</span>
      <span class="gloss" title="smart">קלוג</span>
      <span class="gloss" title="coffee">קאַװע</span>
      <span class="phrase">(די קאַװע)</span>
      <span class="gloss" title="thanks">דאַנק</span>
      <span class="phrase">(אַ דאַנק!)</span>
      <span class="gloss" title="cold">קאַלט</span>
      <span class="phrase">(דער טײ איז קאַלט.)</span>
      <span class="gloss" title="drinks">טרינקט</span>
      <span class="phrase">(דאָס קינד טרינקט טיי.)</span>
      <span class="gloss" title="come">קום</span>
      <span class="phrase">(קום, לאָמיר גײן אין דרױסן.)</span>
      <span class="phrase">(דאָס קינד קען זינגען!)</span>
      <span class="phrase">(זי איז קלײן אָבער קלוג!)</span>
      <span class="phrase">(װעלװל, איר װילט קאַװע?)</span>
      <span class="phrase">(יאָ, אַ דאַנק.)</span>
      <span class="phrase">(די קאַװע איז נישט קאַלט?)</span>
      <span class="phrase">(נײן, די קאַװע איז בעסער װי אין באָסטאָן.)</span>
      <span class="phrase">(װעלװל טרינקט קאַװע אָבער דער טאַטע טרינקט טײ!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-18-hey.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-18-hey.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-18-hey.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ה</span>
      <span class="gloss" title="hungry">הונגעריק</span>
      <span class="gloss" title="herring">הערינג</span>
      <span class="phrase">(דער הערינג)</span>
      <span class="gloss" title="dog">הונט</span>
      <span class="phrase">(דער הונט)</span>
      <span class="phrase">(דער הונט טרינקט װאַסער.)</span>
      <span class="gloss" title="home">היים</span>
      <span class="phrase">(די הײם)</span>
      <span class="gloss" title="is called">הייסט</span>
      <span class="phrase">(ער הייסט װעלװל.)</span>
      <span class="gloss" title="here">אַהער</span>
      <span class="phrase">(קום אַהער!)</span>
      <span class="gloss" title="has">האָט</span>
      <span class="phrase">(זי האָט אַ באַל.)</span>
      <span class="gloss" title="hot">הייס</span>
      <span class="phrase">(דער טיי איז הייס.)</span>
      <span class="phrase">(מיר זײַנען הונגעריק.)</span>
      <span class="phrase">(לאָמיר גײן עסן הערינג.)</span>
      <span class="phrase">(דער הונט איז אין דער הײם!)</span>
      <span class="phrase">(ער הײסט לאַבזיק. קום אַהער, לאַבזיק!)</span>
      <span class="phrase">(לאַבזיק האָט ליב רײנען!)</span>
    </p>
  </div>
  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-19-pey.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-19-pey.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-19-pey.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">פּ</span>
      <span class="gloss" title="park">פּאַרק</span>

      <span class="phrase">(דער פּאַרק)</span>
      <span class="gloss" title="apple">עפּל</span>
      <span class="phrase">(דער עפּל)</span>
      <span class="phrase">(דער עפּל איז רויט און קאַלט.)</span>
      <span class="gloss" title="jump">שפּרינג</span>
      <span class="phrase">(שפּרינג נישט אין דער הײם!)</span>
      <span class="gloss" title="pirate">פּיראַט</span>
      <span class="phrase">(דער פּיראַט)</span>
      <span class="phrase">(דער פּיראַט איז בײז?)</span>
      <span class="gloss" title="parrot">פּאָפּוגײַ</span>
      <span class="phrase">(דער פּאָפּוגײַ)</span>
      <span class="phrase">(דער פּאָפּוגײַ קען רעדן!)</span>
      <span class="gloss" title="poet">פּאָעט</span>
      <span class="phrase">(דער פּאָעט)</span>
      <span class="phrase">(דער מאַן איז אַ פּאָעט.)</span>
      <span class="phrase">(לאַבזיק, לאָמיר גײן אין פּאַרק!)</span>
      <span class="phrase">(רײנע, נעם אַן עפּל!)</span>
      <span class="phrase">(שפּרינג, לאַבזיק, שפּרינג!)</span>
      <span class="phrase">(אין פּאַרק)</span>
      <span class="phrase">(אָ! אַ פּיראַט מיט אַ פּאָפּוגײַ!)</span>
      <span class="phrase">(נישט קײן פּיראַט, נאָר אַ פּאָעט.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-20-khof.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-20-khof.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-20-khof.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">כ</span>
      <span class="gloss" title="daughter">טאָכטער</span>
      <span class="phrase">(די טאָכטער)</span>

      <span class="gloss" title="thinks">טראַכט</span>
      <span class="phrase">(די טאָכטער טראַכט.)</span>
      <span class="gloss" title="laughs">לאַכט</span>
      <span class="phrase">(דאָס מײדל לאַכט.)</span>
      <span class="gloss" title="night">נאַכט</span>
      <span class="phrase">(די נאַכט)</span>
      <span class="phrase">(די נאַכט איז שיין.)</span>
      <span class="gloss" title="bad">שלעכט</span>
      <span class="phrase">(דער הערינג איז שלעכט...)</span>
      <span class="gloss" title="make(you)">מאַכסט</span>
      <span class="phrase">(װאָס מאַכסטו?)</span>
      <span class="phrase">("די טאָכטער טראַכט. זי טראַכט און לאַכט. זי טראַכט און לאַכט און טרינקט בײַ נאַכט.")</span>
      <span class="phrase">(נישט שלעכט...)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-21-langerkhof.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-21-langerkhof.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-21-langerkhof.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ך</span>
      <span class="gloss" title="I">איך</span>
      <span class="phrase">(איך בין נישט דאָ.)</span>
      <span class="phrase">(איך שרײַב.)</span>
      <span class="gloss" title="milk">מילך</span>
      <span class="phrase">(די מילך)</span>
      <span class="phrase">(די מילך איז גוט.)</span>
      <span class="gloss" title="book">בוך</span>
      <span class="phrase">(דאָס בוך)</span>
      <span class="phrase">(דאָס בוך איז שלעכט.)</span>
      <span class="gloss" title="also">אױך</span>
      <span class="phrase">(איך בין אױך אַ פּיראַט.)</span>
      <span class="phrase">(באָבע, װאָס מאַכסטו?)</span>
      <span class="phrase">(גוט! איך טרינק מילך.)</span>
      <span class="phrase">(דאָס איז אַ בוך מיט מײַנע לידער.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-22-fey.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-22-fey.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-22-fey.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">פֿ</span>
      <span class="gloss" title="fish">פֿיש</span>
      <span class="phrase">(דער פֿיש)</span>
      <span class="phrase">(דער פֿיש איז שלעכט.)</span>
      <span class="phrase">(דער פּאָעט עסט דעם פֿיש.)</span>
      <span class="gloss" title="fire">פֿײַער</span>
      <span class="phrase">(דאָס פֿײַער)</span>
      <span class="gloss" title="fruit">פֿרוכט</span>
      <span class="phrase">(די פֿרוכט)</span>
      <span class="phrase">(אַן עפּל איז אַ פֿרוכט.)</span>
      <span class="gloss" title="falls">פֿאַלט</span>
      <span class="phrase">(די פֿרוכט פֿאַלט.)</span>
      <span class="gloss" title="need">דאַרפֿן</span>
      <span class="phrase">(זײ דאַרפֿן עסן.)</span>
      <span class="gloss" title="pepper">פֿעפֿער</span>
      <span class="phrase">(דער פֿעפֿער)</span>
      <span class="gloss" title="from">פֿון</span>
      <span class="phrase">(איך קום פֿון לאָנדאָן.)</span>
      <span class="phrase">(עס איז דאָ אַ פֿיש!)</span>
      <span class="phrase">(איר זעט דאָס פֿײַער? עס איז רױט!)</span>
      <span class="phrase">(די פֿרוכטן פֿאַלן אין דעם פֿײַער!)</span>
      <span class="phrase">(מיר דאַרפֿן גײן!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-23-langerfey.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-23-langerfey.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-23-langerfey.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ף</span>
      <span class="gloss" title="need">דאַרף</span>
      <span class="phrase">(איך דאַרף עסן.)</span>
      <span class="gloss" title="on, at;(pronounced 'af')">אויף</span>
      <span class="phrase">(עס זײַנען דאָ בלײַערס אויף דעם טיש.)</span>
      <span class="gloss" title="sharp, spicy">שאַרף</span>
      <span class="phrase">(דער פֿעפֿער איז שאַרף.)</span>
      <span class="gloss" title="paragraph">פּאַראַגראַף</span>
      <span class="phrase">(דער פּאַראַגראַף)</span>
      <span class="phrase">(איך שרײַב דעם פּאַראַגראַף.)</span>
      <span class="phrase">(איך דאַרף אױך גײן.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-24-tsadek.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-24-tsadek.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-24-tsadek.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">צ</span>
      <span class="gloss" title="concert">קאָנצערט</span>
      <span class="phrase">(דער קאָנצערט)</span>
      <span class="gloss" title="center">צענטער</span>
      <span class="phrase">(דער צענטער)</span>
      <span class="gloss" title="dance">טאַנצן</span>
      <span class="phrase">(זײ טאַנצן)</span>
      <span class="gloss" title="sit">זיצן</span>
      <span class="phrase">(מיר זיצן)</span>
      <span class="gloss" title="room">צימער</span>
      <span class="phrase">(דער צימער)</span>
      <span class="phrase">(דער צימער איז קאַלט.)</span>
      <span class="phrase">(דער פֿיש איז אין דעם צימער.)</span>
      <span class="gloss" title="to">צו</span>
    <span
      class="phrase">(מיר גײען אױף אַ קאָנצערט אין צענטער פֿון פּאַרק.)</span>
      <span class="phrase">(מע קען טאַנצן אױף דעם קאָנצערט?)</span>
      <span class="phrase">(נײן, אָבער מע קען זיצן.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-25-langertsadek.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-25-langertsadek.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-25-langertsadek.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">ץ</span>
      <span class="gloss" title="cat">קאַץ</span>
      <span class="phrase">(די קאַץ)</span>
      <span class="gloss" title="black">שװאַרץ</span>
      <span class="phrase">(דער פֿעפֿער איז שװאַרץ.)</span>
      <span class="gloss" title="dance">טאַנץ</span>
      <span class="phrase">(איך טאַנץ מיט דער קאַץ.)</span>
      <span class="gloss" title="sit">זיץ</span>
      <span class="phrase">(איך זיץ אין פּאַרק.)</span>
      <span class="gloss" title="orange(fruit)">מאַראַנץ</span>
      <span class="phrase">(דער מאַראַנץ)</span>
      <span class="phrase">(דער מאַראַנץ איז אױף דעם טיש אין דעם צימער.)</span>
      <span class="gloss" title="salt">זאַלץ</span>
      <span class="phrase">(דאָס זאַלץ)</span>
      <span class="phrase">(דאָס זאַלץ איז מיט דעם פֿעפֿער.)</span>
      <span class="phrase">(װוּ איז לאַבזיק?)</span>
      <span class="phrase">(ער איז נישטאָ...)</span>
      <span class="phrase">(אָבער דאָ איז אַ קאַץ!)</span>
      <span class="phrase">(די קאַץ איז שװאַרץ.)</span>
      <span class="phrase">(טאַטע! מאַמע! װעלװל! דאָ איז מײַן קאַץ!)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-26-zayenshin.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-26-zayenshin.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-26-zayenshin.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">זש</span>
      <span class="gloss" title="frog">זשאַבע</span>
      <span class="phrase">(די זשאַבע)</span>
      <span class="phrase">(די זשאַבע איז גרין און קאַלט.)</span>
      <span class="gloss" title="orange(color)">אָראַנזש</span>
      <span class="phrase">(דער מאַראַנץ איז אָראַנזש.)</span>
      <span class="gloss" title="giraffe">זשיראַף</span>
      <span class="phrase">(דער זשיראַף)</span>
      <span class="phrase">(דער זשיראַף איז אָראַנזש?)</span>
      <span class="gloss" title="journal">זשורנאַל</span>
      <span class="phrase">(דער זשורנאַל)</span>
      <span class="phrase">(איך זיץ און לײען דעם זשורנאַל.)</span>
    </p>
  </div>

  <div class="section">
    <audio controls>
      <source
        src="<?php print $audio_base; ?>/reading-practice-27-tesshin.ogg"
        type="audio/ogg">
      <source
        src="<?php print $audio_base; ?>/reading-practice-27-tesshin.mp3"
        type="audio/mpeg">
      Your browser does not support the audio element. Please use a recent
      version
      of Mozilla Firefox, Google Chrome, or Internet Explorer 9 or greater.
      To download the audio file instead <a
        href="audio/reading-practice-27-tesshin.mp3">click here</a>.
    </audio>

    <p>
      <span class="letter">טש</span>
      <span class="gloss" title="cholent">טשאָלנט</span>
      <span class="phrase">(דער טשאָלנט)</span>
      <span class="phrase">(מיר עסן טשאָלנט.)</span>
      <span class="gloss" title="check">טשעק</span>
      <span class="phrase">(דער טשעק)</span>
      <span class="phrase">(איך שרײַב אַ טשעק.)</span>
      <span class="gloss" title="champion">טשעמפּיאָן</span>
      <span class="phrase">(דער טשעמפּיאָן)</span>
      <span class="phrase">(דער ברודער איז אַ טשעמפּיאָן.)</span>
    </p>
  </div>
</div>
