<div class="columns">
  <div class="centerfix">
    <div class="centerfix-inner">
      <ul>
        <li>כ</li>
        <li>נ</li>
        <li>מ</li>
        <li>צ</li>
        <li>פֿ</li>
      </ul>

      <ul class="prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
        <li data-value="3"></li>
        <li data-value="4"></li>
        <li data-value="5"></li>
      </ul>

      <ul class="reply">
        <li data-value="4">ץ</li>
        <li data-value="1">ך</li>
        <li data-value="5">ף</li>
        <li data-value="3">ם</li>
        <li data-value="2">ן</li>
      </ul>
    </div>
    
    <div class="button">
      <button class="checkAnswers">Check answers</button>
      <button class="reload">Reload exercise</button>
    </div>
    <div class="dialog"></div>
  </div>
</div>
