<div class="columns">
  <ul class="letter-name">
    <li>komets alef <br/><span class="letter-sound"><em>o</em> as in m<em>o</em>re</span></li>
    <li>vov yud <br/><span class="letter-sound"><em>oy</em> as in b<em>oy</em></span></li>
    <li>tsvey yudn <br/><span class="letter-sound"><em>ay</em> as in h<em>ay</em></span></li>
    <li>ayen <br/><span class="letter-sound"><em>e</em> as in b<em>e</em>d</span></li>
    <li>pasekh tsvey yudn <br/><span class="letter-sound"><em>ai</em> as in ch<em>ai</em></span></li>
    <li>pasekh alef <br/><span class="letter-sound"><em>a</em> as in c<em>a</em>r</span></li>
    <li>vov <br/><span class="letter-sound"><em>oo</em> as in m<em>oo</em>n</span></li>
    <li>yud <br/><span class="letter-sound"><em>i</em> as in g<em>i</em>ve</span></li>
  </ul>

  <ul class="prompt" id="leftmarginfix">
    <li data-value="1"></li>
    <li data-value="2"></li>
    <li data-value="3"></li>
    <li data-value="4"></li>
    <li data-value="5"></li>
    <li data-value="6"></li>
    <li data-value="7"></li>
    <li data-value="8"></li>
  </ul>

  <ul class="reply" id="rightmarginfix">
    <li data-value="1">אָ</li>
    <li data-value="8">י</li>
    <li data-value="3">ײ</li>
    <li data-value="2">ױ</li>
    <li data-value="7">ו</li>
    <li data-value="5">ײַ</li>
    <li data-value="6">אַ</li>
    <li data-value="4">ע</li>
  </ul>
</div>

<div class="button">
  <button class="checkAnswers">Check answers</button>
  <button class="reload">Reload exercise</button>
</div>

<div class="dialog"></div>
