<div class="columns">
  <div class="centerfix">
    <div class="centerfix-inner">
      <ul>
        <li>בֿ</li>
        <li>ח</li>
        <li>ת / שׂ</li>
        <li>כּ</li>
        <li>תּ</li>
      </ul>

      <ul class="prompt">
        <li data-value="1"></li>
        <li data-value="2"></li>
        <li data-value="3"></li>
        <li data-value="4"></li>
        <li data-value="5"></li>
      </ul>

      <ul class="reply">
        <li data-value="4">ק</li>
        <li data-value="2">כ</li>
        <li data-value="5">ט</li>
        <li data-value="3">ס</li>
        <li data-value="1">װ</li>
      </ul>
    </div>
    <div class="button">
      <button class="checkAnswers">Check answers</button>
      <button class="reload">Reload exercise</button>
    </div>
    <div class="dialog"></div>
  </div>
</div>
